### ISSUE TITLE
Fix appveyor "release to github" deployment

### ISSUE THREAD

**Issue by bdejong** [bdejong/smartelectronix#10]
Currently I get:

```
Packaging artifacts...OK
Skip "GitHub" deployment as environment variable has not matched ("appveyor_repo_tag" is "false", should be "true")
Build success
```

Which is weird. This might have to do with the fact that I'm using `git push --follow-tags` rather than separate `push` and `push --tags`, or... something else.

The documentation is a bit.... dense:
https://www.appveyor.com/docs/deployment/github

**Comment by bdejong** [comment]
http://help.appveyor.com/discussions/problems/4766-cant-get-the-deployment-settings-right

**Comment by bdejong** [comment]
@dozius maybe you have more luck ;) The Travis build is pushing the plugins to the releases already:
https://github.com/bdejong/smartelectronix/releases

**Comment by dozius** [comment]
Maybe this will help? Seems to be a similar issue. Points to another thread with more details as well.

http://help.appveyor.com/discussions/questions/2133-deploy-setting-for-nuget

Unfortunately I am not familiar with appveyor. I will need to do some reading when I have more time.
