### ISSUE TITLE
Modular build

### ISSUE THREAD

**Issue by dozius** [bdejong/smartelectronix#3]
Create modular build system for all plugins

**Comment by dozius** [comment]
I created this so we could move discussion and work related to this feature here instead of on the old pull request.

**Comment by dozius** [comment]
WIndows build still works.

I am not 100% sure if Cmake works similar to qmake but with qmake you generally have a top level project file which calls up sub projects. From my brief reading it looks like Cmake does this with add_subdirectory(). So in the end I think it would look something like...

Top level CMakeLists.txt
`
# Common stuff that will be inherited in sub projects

add_subdirectory(smexoscope)
add_subdirectory(Bouncy)
... etc.
`

Project level CMakeLists.txt

'
project(Smexoscope)

# Project specific stuff
'

So you would want to put the functions in the top level project or even just set variables that projects can use.

p.s. Maybe we should open an issue for 'modular build' and move discussion there?

**Comment by dozius** [comment]
It looks like cmake supports including other cmake files as well. So we could even set it up so there is one top level project to build all modules and modules can also be built stand alone. I think standardizing the project structure would go a long way to re-usability in the build script as well.

Something like...

CMakeLists.txt
common.txt
project1
  |- CMakeLists.txt
  |- res
  |  |- *.png
  |  |- *.rc
  |- src
  |   |- *.hpp
  |   |- *.cpp
project2
  |- CMakeLists.txt
  |- res
  |  |- *.png
  |  |- *.rc
  |- src
  |   |- *.hpp
  |   |- *.cpp
  
With enough structure the project CMakeLists.txt would be a single include and function call, something like...
```
include ../common.txt

some_build_function(project1_name, GUI)
```
```
include ../common.txt

some_build_function(project2_name, NOGUI)
```

The top level would just become a bunch of add_subdirectory() calls.

**Comment by dozius** [comment]
I did some initial work on this. Check it out in this branch on my fork.

https://github.com/dozius/smartelectronix/tree/feature/modular-build

Still needs some cleanup (standard file structure per module, add more modules, naming, etc.) but the core concept is there. Common.txt has all the reusable functions and the module cmake files are reduced to a single function call after including common.txt and calling project(). Should be expandable by adding build_au() or other such functions to common.txt later on. 

Windows build works, please test the Mac build.

Let me know what you think! :smiley:

**Comment by bdejong** [comment]
This looks really nice!

Some comments:

- I had been looking at this before and the only problem I have with this approach is that it becomes impossible to build only one project, or you have to start doing command line trickery like described [here](http://techminded.net/blog/modular-c-projects-with-cmake.html). This makes running cmake no longer super simple. But perhaps this is OK. Maybe there is a nicer fix...?
- I don't really like the GLOB approach. I think this results in lazy programming and no longer caring which files are included and which not... I think having an approach with manually set cpp/h/bmp/png files makes more sense as it forces you to find out things like "smexoscope has twice the same PNG".
- [Bouncy](https://github.com/dozius/smartelectronix/tree/feature/modular-build/Bouncy) was already changed to support the new version of the VST SDK, it could be the proof of the pudding. Only issue is that the build on windows uses intrinsics and as such might be more complicated than building on mac, which uses plain old standard C++.

**Comment by bdejong** [comment]
( btw, I created a bunch of issues while I was looking through the code: https://github.com/bdejong/smartelectronix/issues )

**Comment by dozius** [comment]
Thanks!

1. I also wanted to avoid this. Fortunately I had this mind when working. The way I have it setup now this shouldn't be a problem. For example, you can go into the Smexoscope directory, run cmake and build just that project or run cmake in top level and build all projects. There is also the option, at least in visual studio, to load up the top level solution and build single projects from there.

2. I 100% agree. I wanted to see how far I could go for the concept. Having gone to the extreme It's now easy to reel it back in a bit by having project specific source variables etc. I will give this a shot.

3. Sounds like a good way to test it out. I will try adding Bouncy to the build system next.

**Comment by bdejong** [comment]
Nice! It's always good to know someone else thinks the same way...

Thanks for your help man!!!!

**Comment by bdejong** [comment]
Hmm, there is something off about your modular build.

ne one

**Comment by bdejong** [comment]
Moving `set_source_files_properties(${TARGET_PNG} PROPERTIES MACOSX_PACKAGE_LOCATION Resources)` to add_vstgui seems to work...

**Comment by bdejong** [comment]
Another nitpick: one function takes `target` another takes `target_name`.

**Comment by bdejong** [comment]
BTW, let's start a pull request an do the code reviews in there...

**Comment by bdejong** [comment]
Aaaaand another nitpick: common.txt should go into the Common directory :)

**Comment by dozius** [comment]
Sorry about that. Looks like as I was restructuring things some of the Mac stuff slipped through the cracks, as well as things getting duplicated. I had several iterations moving things around. Wish I could test both platforms at the same time so I wouldn't miss these things.

Yeah, it is still a big mess! :laughing: It is why I haven't made a pull request yet. Not ready for prime time. I was just happy to have something that worked at the end of last night. Cmake documentation isn't exactly enlightening. :sob:

I should have some time this weekend to clean things up, implement your suggestions (thanks for all the feedback!) and get it ready for a PR so we can review it there.

**Comment by bdejong** [comment]
I started to set up travis ci. Should be able to build automatically on branches etc on an OS X machine. Good for debugging :)

**Comment by dozius** [comment]
Nice!

**Comment by bdejong** [comment]
With a bit of luck I just got it working... You can already see the build status in the readme...!

**Comment by bdejong** [comment]
Yup, it's working:

```
$ cmake .
CMake Error: The source directory "/Users/travis/build/bdejong/smartelectronix" does not appear to contain CMakeLists.txt.
```

So, if you set up a pull request with a cmake file in the root you should be getting results automatically in the pull request!

**Comment by dozius** [comment]
Nice work! This will come in very handy.

**Comment by bdejong** [comment]
OK, got everything working for OSX, not yet for AppVeyor (windows builds!). When you make a pull request, make sure you adapt https://github.com/bdejong/smartelectronix/blob/master/.travis.yml

By just just changing

```
- cmake Smexoscope
```

to 

```
- cmake .
```

**Comment by bdejong** [comment]
Cool, I got it to work for windows too :-)

- OS X: https://travis-ci.org/bdejong/smartelectronix
- Windows: https://ci.appveyor.com/project/bdejong/smartelectronix

For windows perhaps you could have a look at the calls because it would be better to build 64 bit versions. I think it might be just "cmake -G "Visual Studio 14 x64" Smexoscope" or something, but I'm driving blind :D

**Comment by dozius** [comment]
This is awesome! Just added PR and watched the magic. Looks like everything checked out. :smile:
