### ISSUE TITLE
Update readme to specify valid Python version for vstsdk script

### ISSUE THREAD

**Issue by etheory** [bdejong/smartelectronix#30]
In the readme it says to run:
python get_steinberg_sdk.py

which doesn't work in python 3.x, but does in 2.x

so either it'd be good to update the readme, or update the script to support both python versions.

Error message is:
****Audio\smartelectronix_2>python get_steinberg_sdk.py
  File "get_steinberg_sdk.py", line 15
    print "{}%".format(progress)

Which looks easy enough to fix. Once I send you my signed NDA I'll add a PR.

**Comment by bdejong** [comment]
👍 !

**Comment by bdejong** [comment]
@etheory any update on this? this should be an easy PR...

**Comment by etheory** [comment]
Sorry, I'm busy most nights preparing for Christmas at home this year, but I'm trying to find time to work on this stuff in between. After the next week or so I'll be able to dedicate more time to it.

**Comment by bdejong** [comment]
get_steinberg_sdk now works with both py2 and py3.

**Comment by etheory** [comment]
Bugger the PR I was about to submit is literally almost exactly the same as yours ;-)

**Comment by bdejong** [comment]
sorry 😊
