### ISSUE TITLE
supaphaser GUI crash

### ISSUE THREAD

**Issue by JurekRaben** [bdejong/smartelectronix#31]
Crashes on OSX 10.9.4 using Renoise 3.1 64bit under some specific scenario. Renoise just says "GUI crash", and then emergency-saves the song.

Steps to reproduce:
1. Renoise 3.1 64 bit, put plugin into track
2. Move all sliders and controls to minimum position (left / down)
3. Save song
4. Reload same song -> crash appears

**Comment by bdejong** [comment]
@JurekRaben could you please try to reproduce this with another VST host too?

**Comment by JurekRaben** [comment]
Hi,

I am now on Sierra 10.12.6. I repeated the above steps, but it does not crash anymore. I have seen similar crashes in other plugins, too, which then disappeared by updating to a higher macos version.

So I would assume that problem disappeared. But if you are interested in further tests (on macos 10.12.6), please let me know.

**Comment by bdejong** [comment]
No, that's fine. I'll go ahead and close this one...
