### ISSUE TITLE
how to compile s(M)exoscope for 64-bit macOS AudioUnit??

### ISSUE THREAD

**Issue by esaruoho** [bdejong/smartelectronix#41]
Hi, how do I compile s(M)exoscope so that it works as a 64-bit AudioUnit on macOS High Sierra?

**Comment by bdejong** [comment]
hey Esa,

sorry, there is no AU version of any of the plugins here. All Au ports used to be done by DestroyFX and used some proprietary library of theirs.

however, this guy maintains an AU port: http://armandomontanez.com/smexoscope/

Bram
