### ISSUE TITLE
build instruction error

### ISSUE THREAD

**Issue by CJunit** [bdejong/smartelectronix#42]
Being a mostly non-coder noob I am no doubt missing obvious things, but my attempts to follow your instructions aren't working. I do as specified:

> git submodule update --init --recursive
> python get_steinberg_sdk.py
> cmake .

...and soon get this error:

> -- Detecting CXX compile features - done
> CMake Error at AnechoicRoomSimulator/CMakeLists.txt:3 (include):
>   include could not find load file:
> 
>     /home/cjunit/Code/smartelectronix/AnechoicRoomSimulator/../common/common.cmake
> 
> 
> CMake Error at AnechoicRoomSimulator/CMakeLists.txt:5 (pre_build):
>   Unknown CMake command "pre_build".
> 
> 
> -- Configuring incomplete, errors occurred!

The specified file IS in the git clone root at "/common/common.cmake". It seems to me that some step is probably missing. Am I supposed to run "cmake ." from some other directory? I am stuck on what is probably a very simple problem.

**Comment by bdejong** [comment]
Could you try updating cmake to the latest version? Other than that I don't
really have any bright ideas. It looks like you're doing the right steps!
