### ISSUE TITLE
Active? And Question about Surge?

### ISSUE THREAD

**Issue by baconpaul** [bdejong/smartelectronix#46]
Hi!

Not sure if you are active here. But I’m one of the maintainers on Surge (https://surge-synthesizer.github.io/) a free and open source synth. We are about to do our 1.8 release and in that release we integrated quite a bit of open source software from elsewhere into the Surge signal path including filters from Odin, and effects from Airwindows.

Looking at our 1.9 release we came across this repo and were thinking that some of these FX would be lovely FX in the surge chain also. Would probably integrate them similarly to how we did Airwindows (namely have a ‘Airwindows’ effect with sub-types). And we are GPL3 and you are GPL3.

But before we go and do something like that, we like to ask folks. Would you be OK if we integrated some of these effects (with full credit to you and authors of course) into the surge signal path?

Thanks for releasing free and open source audio software! And Happy new Year!

**Comment by bdejong** [comment]
Hey Paul,

Go ahead! For contributions to these plugins I use a CLA, but for inclusion into other projects there is no such requirement.

These plugins are not actively developed. I wrote them many, many moons ago. So some of the code is.... Dubious quality, so tread carefully. 😉

Greetings,

Bram

**Comment by baconpaul** [comment]
Ha cool thanks Bram! Will let you know here if we do end up integrating some or any. Appreciated. Will close this for now.

**Comment by nodanaonlyzuul** [comment]
As a long time fan of the original smartelectronix plugins and a newish convert to Surge I'm really excited by this!

**Comment by baconpaul** [comment]
@nodanaonlyzuul if you happen to also be a C++ programmer, and want to sling some code with us in surge land, would be happy to have you on board! (No pressure, just a welcoming offer). Probably best to hop on our discord if that interests you.
