### ISSUE TITLE
Use std::string for everything

### ISSUE THREAD

**Issue by bdejong** [bdejong/smartelectronix#7]
All parameter getting and setting should really be done with std::string and stringstream for concatenating/etc... This would be so much cleaner...!

**Comment by etheory** [comment]
I'd recommend against it, performance wise it's not great....
It's just as easy to use sprintf and then not have the overhead of all the memory allocation and copying done by std::string.

**Comment by bdejong** [comment]
As all of this is in the non-heavily-processing paths this should be fine. That said, I think this is a massive change that would require a lot of work, so most likely not doing this anyway ;)

**Comment by etheory** [comment]
The problem that most programs these days have, is that there are code paths that ignore the most efficient, optimal, low memory, high-speed solutions. IMO it doesn't matter which part of the code it is, simplicity isn't always the best option. YMMV.
